### ISSUE TITLE
RESEARACH: initial discovery

### ISSUE THREAD

**Issue by gentilim** [redarrowlabs/tournavation-2015#1]
Research session 10/30/15

Journy mapping

**Comment by gentilim** [comment]
Updated the wiki.

Attached info presented at 11/4 meeting.
[Meeting 15-11-4.pdf](https://github.com/redarrowlabs/tournavation-2015/files/28101/Meeting.15-11-4.pdf)

**Comment by hbarrette** [comment]
Attached info presented at 11/11 meeting.
Attached map of observations from brainstorm at 11/11 meeting.
[MappingObservations_15-11-11.pdf](https://github.com/redarrowlabs/tournavation-2015/files/33258/MappingObservations_15-11-11.pdf)
[Meeting 15-11-11.pdf](https://github.com/redarrowlabs/tournavation-2015/files/33259/Meeting.15-11-11.pdf)
