### ISSUE TITLE
User Story: Sign in with my Google account

### ISSUE THREAD

**Issue by atquail** [redarrowlabs/tournavation-2015#14]
As a participant (student), I want to be able to sign into the application with my google account, so that I can start to record my health behavior.

+Scenario 1: Sign in with my Google account+
Given that I want to record my health behaviors
When I go to sign into the application
Then I am able to sign in using my Google account

**Comment by atquail** [comment]
I think we'll need to discuss this story & scenario a bit more before development can start.  I think Google was selected as a frictionless approach for this first iteration.  We're anticipating that users will be able to use social media accounts to sign into the application (those should be separate stories for a future iteration).  In addition there was also discussion of signup features down the road (using an e-mail address, or something).  

There may also need to be a story around a "sign in" page, or at least some discussions around that user experience before we're ready to pick this story up.

**Comment by nateconroy** [comment]
Thanks for this discussion atquail! Google sign in might be frictionless but not universally available across schools. Another concern is trying to make sure that identifying information on students is not collected. One potential way around this is to have a teacher log in using their public school email, and then having students log in after that with their student ID number.  

Agreed, more discussion around sign in is needed.
