### ISSUE TITLE
User Story: Basic site header & footer

### ISSUE THREAD

**Issue by atquail** [redarrowlabs/tournavation-2015#16]
As a participant, I need to see a simpler site footer, so that I can easily verify that I am properly accessing HealthHero.

Scenario 1:  Viewing Site Footer
Given that the HealthHero website is accessible by participants
When participants visit all of the site pages
Then they will see a consistent site footer with "HealthHero" text

Scenario 2:  Viewing Site Header
Given that the HealthHero website is accessible by participants
When participants visit all of the site pages
Then they will see a consistent site header

Scenario 3: Privacy Header 
Given that I logged in with a valid Google account
When I locate the site header
Then I only see my first name (from my Google account)

**Comment by atquail** [comment]
The 3rd scenario here assumes that we've got the Google login feature completed.  I believe @cnickeson was on that story.

**Comment by mjkraner** [comment]
Testing completed
