### ISSUE TITLE
Tracking Metrics on Paper

### ISSUE THREAD

**Issue by hbarrette** [redarrowlabs/tournavation-2015#3]
We’re looking for some volunteers (or their kids!) to track manually some of the metrics from our brainstorming.  We’re looking for variance in the data over time that can lead to critical thinking observations.

Please include the age of the person taking the measurements and grade in school (if applicable).

Share you initial experience with tracking metrics at the meeting next Wednesday.

Tasks
- Pick a Measurement (or more than 1)
- Track your observations on Pen & Paper
- Bring us your tracking paper

Variables to Consider Including
- Date
- Time(s) of Day 
- Affect on Mood, Tiredness, Focus, or Hunger
- Units - Be specific in which units your using

Measurements
- Water Intake (vs other drinks)
- Hours Slept
- Activity Level (Steps, Type of Activity)
- Weight
- Hours Slept
- Heart Rate (Recovery, Resting, Active)
- Reflex Timing
- Flexibility
- Jump Height/Distance
- Calorie Counting
- Salt Intake (for package food)
- Sugar Intake (for package food)
- Cognitive Measurement
- Work - Weight/Distance/Time
- Nutritional Literacy (Test)
- Blood Pressure

**Comment by jerry-locke** [comment]
I've got a step counter that I've been taking measurements with. Are we still looking to collect/share this information?

**Comment by aaronmkrueger** [comment]
I also brought in a blood pressure cuff if that's something you'd see as valuable
