### ISSUE TITLE
Adding minutes to the text output of "Record Sleep"

### ISSUE THREAD

**Issue by chrismbayer** [redarrowlabs/tournavation-2015#34]
This is an enhancement to issue #6  The goal is to add additional detail to the text output. With this enhancement, output will now include hours + minutes of sleep. 

+Scenario 1: I went to bed yesterday+
Given that today is Wednesday
And the time I went to bed is 11pm on Tuesday (yesterday)
When I try to record my sleep for Wednesday
And I record my bed time as 11:00 PM
And record my wake time as 06:28 AM
Then I am to record 7 hours and 28 minutes of sleep

+Scenario 2:  Went to bed "today"+
Given that today is Wednesday
And the time I went to bed is 01:00 AM of Wednesday (today)
When I try to record my sleep for Wednesday
And I record my bed time as 01:00 AM
And record my wake time as 06:17 AM
Then I am to record 5 hours and 17 minutes of sleep

**Comment by mjkraner** [comment]
Bugs logged, moving story to done
