### ISSUE TITLE
Suggestion: change the sign out link to sign in when not signed into app

### ISSUE THREAD

**Issue by mjkraner** [redarrowlabs/tournavation-2015#57]
Sign out of health heros
view the header
says welcome! and sign out

user is already signed out so link could change to sign in?

![image](https://cloud.githubusercontent.com/assets/16242234/12632965/b2e987f4-c521-11e5-9fd5-fe1c424fea51.png)

**Comment by gentilim** [comment]
Addressed by removing the header when not signed in
