### ISSUE TITLE
User Story: Record sleep

### ISSUE THREAD

**Issue by gentilim** [redarrowlabs/tournavation-2015#6]
As a participant (student), I need to be able to record my sleep, so that I can start tracking my health behavior.

**Assumption:  For the scenarios in this user story, wake time is almost always considered "today".  Total calculated hours should make sense based on the bed/wake time.**

+Scenario 1: Time to bed is set before wake up time+
Given start time is set before the end time
And my end (wake) time is considered today
When end time is selected 
Then total hours are calculated

+Scenario 2: Went to bed yesterday, woke up today+
Given that today is Wednesday
And the time I went to bed is 11pm on Tuesday (yesterday)
When I try to record my sleep for Wednesday
And I record my bed time as 11pm
And record my wake time as 6am
Then I am to record 7 hours of sleep

+Scenario 3: Went to bed today, woke up today+
Given that today is Wednesday
And the time I went to bed is 1am of Wednesday (today)
When I try to record my sleep for Wednesday
And I record my bed time as 1am
And record my wake time as 6am
Then I am to record 5 hours of sleep

+Scenario 4: I went to bed yesterday, woke up today+
Given that today is Wednesday
And the time I went to bed is 9pm on Tuesday (yesterday)
When I try to record my sleep for Wednesday
And I record my bed time as 9pm
And record my wake time as 12am
Then I am to record 3 hours of sleep

+Scenario 5: I went to bed yesterday, woke up yesterday+
Given that today is Wednesday
And the time I went to bed is 9pm on Tuesday (yesterday)
When I try to record my sleep for Wednesday
And I record my bed time as 9pm
And record my wake time as 11pm
Then I am to record 2 hours of sleep

**Comment by atquail** [comment]
Could we strengthen this scenario by adding a little more detail around time?

**Scenario 1: Time to bed is set before wake up time**
Given a start time of 12am is set before the end time
When an end time of 6am is selected 
Then a total of 6 hours are calculated

**Comment by atquail** [comment]
I've added two additional story scenarios to clarify some questions that have come up about recording sleep from "yesterday".

**Comment by chrismbayer** [comment]
Made changes and rolling them back to create a separate issue with an enhancement label.

**Comment by atquail** [comment]
Based on feedback from a few bugs logged (#38, #49) I added an assumption to this story, and added in some story scenarios to clarify the "yesterday" and "today" scenarios.  Total calculated hours should make sense based on the bed/wake time.
